services:
  - type: web
    name: train-app
    env: node
    buildCommand: |
      cd frontend && npm install && npm run build
      cd ../server && npm install
    startCommand: node server/index.js
    rootDir: .
